### ISSUE TITLE
Unable to upload firmware

### ISSUE THREAD

**Issue by gsuresh2u** [bigtreetech/Octopus-Max-EZ#1]
Hi, i installed klipper in Pi, then generated klipper.bin file and downloaded, renamed it to firmware.bin
after inserttting the file to sd card, it uploaded fine (file name changed to FIRMWARE.CUR)
But klipper not connected witth msu, i am getign mcu serial fine
then tried to flash firmware again with other klipper.bin
then its not uplaoding firmware, file name remains the same
then i tried to connected to pc, then it showing as COM6
then i tried to upload Marlin firmware directly from VS Code, then its saying "unable to find a matching cmsis-dap device"
is there any problem witth bootloader ?
there are 3 buttons on board, RESET, BOOT0, BOOT1, is there any way to reset o facory defaults with those buttons ?
and how to enter DFU mode ? to upload firmware directly from PI using DFU mode ?
i tried with "make flash FLASH_DEVICE=1d50:614e"
that 1d50:614e is showinf as usb serial in putty with command "lsusb"
![usb](https://user-images.githubusercontent.com/39871361/220257734-b926760a-77aa-4a47-916b-92c0779ad17a.jpg)
![Serial](https://user-images.githubusercontent.com/39871361/220257735-ece9e44a-6c22-4407-8910-1e28506cb3ac.jpg)

**Comment by gsuresh2u** [comment]
@bigtreetech, please help me to reset board to factory default

**Comment by gsuresh2u** [comment]
It's ok

**Comment by gsuresh2u** [comment]
Close

**Comment by KumphanartDansiri** [comment]
@gsuresh2u Do you able to reset the board to factory default?  After flashing firmware.bin, I am no longer see the serial and want to reset it back.

**Comment by KumphanartDansiri** [comment]
@gsuresh2u Can you provide your klipper firmware?
