### ISSUE TITLE
esp32 conflicting tx and rx pins

### ISSUE THREAD

**Issue by ellensp** [bigtreetech/Octopus-Max-EZ#16]
on https://github.com/bigtreetech/Octopus-Max-EZ it says

ESP-RX(UART7) | PE7 | 58
ESP-TX(UART7) | PE8 | 59

but on https://github.com/bigtreetech/Octopus-Max-EZ/blob/master/Hardware/BIGTREETECH%20Octopus%20MAX%20EZ%20V1.0%20PinOut.png
It says

PD8 USART3_TX
PD9 USART3_RX

And no Circuit diagrams, so cannot check those ....

Which one is correct?

**Comment by ellensp** [comment]
@bigtreetech please advise. one of these two documents is wrong and needs updated

**Comment by bigtreetech** [comment]
`ESP-RX(UART7) | PE7 | 58` is correct, pinout fixed in https://github.com/bigtreetech/Octopus-Max-EZ/commit/8a0187f377eba513712de5b5e54163beb42accc0

And  schematic is uploaded in https://github.com/bigtreetech/Octopus-Max-EZ/commit/ddc39ce6675fbb0d8912bab60672a7bc88b93c52
