### ISSUE TITLE
[BUG] Pin PA4 (FAN2) does not support PWM? 

### ISSUE THREAD

**Issue by sargonphin** [bigtreetech/Octopus-Max-EZ#21]
Hello,

Following this issue : https://github.com/MarlinFirmware/Marlin/issues/26625

The fan port FAN2 is only ON/OFF and no PWM is supported.

The board seems to have no hardware support for PWM. Is that just misconfiguration or is it missing from the board datasheet?

See linked issue for details. Any help is appreciated ^_^

**Comment by ellensp** [comment]
"The board seems to have no hardware support for PWM" 

No just just pin PA4, the the rest of the fan pins all have hardware PWM 

This is a limitation of the controller used the STM32H723ZE

**Comment by sargonphin** [comment]
yes sorry lol I wrote this a bit too fast

**Comment by sargonphin** [comment]
Fan header has no hardware PWM output. Must use software PWM. Closing the issue

```
Hello, we apologize for the inconvenience. 
PA4 does not have hardware PWM function and needs to be set to software simulation pwm. 
Marlin needs to open FAN_SOFT_PWM in configuration.h.

Best regards

BIQU
```
